### ISSUE TITLE
How to use on macos?

### ISSUE THREAD

**Issue by brett-anderson** [Qovery/Replibyte#111]
hello! I was wondering the best way to use this on macos. From the docs, I used brew to install:
```
brew install replibyte
```
but when I restart my terminal and run `replibyte`, I get:
```
zsh: command not found: replibyte
```
Brew info:
```
✗ brew info replibyte
qovery/replibyte/replibyte: stable 0.6.3
Seed Your Development Database With Real Data ⚡️
https://github.com/Qovery/replibyte
/usr/local/Cellar/replibyte/0.6.3 (49 files, 275.3KB) *
  Built from source on 2022-05-16 at 10:56:08
From: https://github.com/Qovery/homebrew-replibyte/blob/HEAD/Formula/replibyte.rb
License: MIT
```

brew --cellar replibyte
```
✗ brew --cellar replibyte
/usr/local/Cellar/replibyte
```
Is there a step that I'm missing with brew?

**Comment by evoxmusic** [comment]
Do you have `/usr/local/Cellar` in your local path? Maybe something is missing in the formulae 🤔

Any idea @fabriceclementz ?

**Comment by ederski** [comment]
My Cellar is in `/opt/homebrew/Cellar` and I tried adding a few different things to my path to get it to work but still got command not found:
/opt/homebrew/Cellar
/opt/homebrew/Cellar/replibyte/0.6.0/bin
/opt/homebrew/Cellar/replibyte
/opt/homebrew/Cellar/replibyte/0.6.0

**Comment by fabriceclementz** [comment]
Hi,
I just installed it from homebrew. It was successfully downloaded to `/usr/local/Cellar/replibyte/0.6.3`.

Howewer, I think we need to change this URL https://github.com/Qovery/homebrew-replibyte/blob/main/Formula/replibyte.rb#L5 because it only contains the source code and not the binary of replibyte which is what we want.

I had set up a [test repo](https://github.com/fabriceclementz/homebrew-replibyte/blob/main/Formula/replibyte.rb#L5) and the URL I was using was as follows: `https://github.com/Qovery/replibyte/releases/download/v#{version}/replibyte_v#{version}_x86_64-apple-darwin.zip`

I just downloaded manually https://github.com/Qovery/replibyte/releases/download/v0.6.3/replibyte_v0.6.3_x86_64-apple-darwin.zip and it contains the binary.

@evoxmusic can you try to change this URL in https://github.com/Qovery/homebrew-replibyte ?

**Comment by evoxmusic** [comment]
@fabriceclementz you are right, I've changed the URL you shared, the only issue is that the binary does not have the correct name. I'm looking at our homebrew GithubActions

**Comment by fabriceclementz** [comment]
I've just try it with my repo and I've the same error as you cause the binary name is not correct

```sh
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - replibyte
```

**Comment by evoxmusic** [comment]
I've found the issue, I am giving it a try now. I keep you posted

**Comment by fabriceclementz** [comment]
I think it's these lines which needs to be modified https://github.com/Qovery/Replibyte/blob/main/.github/workflows/on-release.yml#L117-L118

**Comment by evoxmusic** [comment]
@fabriceclementz can you try now?

**Comment by ederski** [comment]
It worked for me! Thanks so much!

**Comment by brett-anderson** [comment]
Worked for me as well. Thanks for the quick turn-around, I'm eager to test this out.
