### ISSUE TITLE
Enhancement: make RepliByte installable from Homebrew

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#34]
Everything is in the title :) Today, it's tedious to install RepliByte from MacOSX. It will be great to make it installable from Homebrew for MacOSX Intel and M1 processors. Anyone can help here? :)

**Comment by michaelgrigoryan25** [comment]
`cargo install https://github.com/qovery/replibyte`?

**Comment by evoxmusic** [comment]
It requires to have cargo installed locally. Which is not suitable for everyone

**Comment by fabriceclementz** [comment]
@evoxmusic 

Binaries are not accepted to homebrew-core https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

We can use this formulae which build the binary but depends on rust (so rust needs to be installed locally :( ) 
I struggle with what to test in the formula because checking the version is considered not sufficient but I can still try to submit to https://github.com/Homebrew/homebrew-core with only a simple version test if you think that we still have to take this road.

```
class Replibyte < Formula
  version = "0.0.13"
  desc "Synchronize your cloud databases and hide sensitive data 🕵️‍♀️"
  homepage "https://github.com/Qovery/replibyte"
  url "https://github.com/Qovery/replibyte/archive/v#{version}.tar.gz"
  sha256 "b711367a1c60fd2dbc389683152a08a7f5605ade311d352d8296f67a70d2fa16"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", "--root", prefix, "--path", "./replibyte"
  end

  test do
    assert_match "/^replibyte 1.0.0\n/", shell_output("#{bin}/replibyte -V")
  end
end
```

Another solution to distribute the binary directly can be to use a custom taps like Planetscale does [here](https://github.com/planetscale/homebrew-tap) so we can install the existing binary in the Github releases archive.

I've made some tests here https://github.com/fabriceclementz/homebrew-replibyte/blob/main/Formula/replibyte.rb and it works.
The installation process is then as follow :

```sh
brew tap fabriceclementz/replibyte
brew install replibyte
```

If you think it's a better approach for now, you can create a repository in which I would make a pull request.

WDYT ? 

For updating the formulae, we can use this Github action https://github.com/dawidd6/action-homebrew-bump-formula. I will make some tests tomorrow.

**Comment by evoxmusic** [comment]
I think the one with `brew tap` is perfect for me. Let me know how you want to proceed

**Comment by evoxmusic** [comment]
Thank you @fabriceclementz ❤️👌🙏

**Comment by evoxmusic** [comment]
@fabriceclementz it's all good 👌🏽 brew is now supported and the GitHub Actions is in place. I can close this ticket.
