### ISSUE TITLE
Use pg_dump instead of pg_dumpall command

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#72]
1. pg_dumpall is too aggressive/stressful for a production database
2. needs superuser permissions which is not possible sometimes (e.g AWS RDS)

**Comment by 2Kable** [comment]
We used VAULT to generate credentials over a RDS's PGSQL database, and we effectively encountered an error:
It made a dump of ~100B, when connecting to the database, so we ran pg_dumpall manually
It failed with the following error:
```
pg_dumpall: error: query failed: ERROR:  permission denied for table pg_authid
pg_dumpall: error: query was: SELECT oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolconnlimit, rolpassword, rolvaliduntil, rolreplication, rolbypassrls, pg_catalog.shobj_description(oid, 'pg_authid') as rolcomment, rolname = current_user AS is_current_user FROM pg_authid WHERE rolname !~ '^pg_' ORDER BY 2
```
This is because all RDS credentials doesn't have the superuser role, which is necessary for pg_dumpall
It seems replibyte, is making a backup of this error log, explaining the very small backup file

As a temporary workaround we made a dump on passed it as stdin (per the documentation)

**Comment by evoxmusic** [comment]
Thank you @2Kable for the details - I keep you posted
